"""initial schema

Revision ID: 0a7d046e9057
Revises: 
Create Date: 2026-08-13 05:10:06.397979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

from alembic_helpers.extensions import ensure_extension

revision: str = '0a7d046e9057'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Must precede any table creation: articles.embedding and stories.embedding are
    # VECTOR columns, so the type has to exist before those CREATE TABLEs run.
    ensure_extension("vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_type', sa.Enum('USER', 'AGENT', 'SYSTEM', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORGANIZATION', 'LOCATION', 'INSTITUTION', 'PARTY', 'OTHER', name='entity_type'), nullable=False),
    sa.Column('canonical_key', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('future_page_slug', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_canonical_key'), 'entities', ['canonical_key'], unique=False)
    op.create_table('events',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geography', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('RSS', 'ATOM', 'WEB', 'YOUTUBE', 'OFFICIAL_RELEASE', 'PRESS_RELEASE', name='source_type'), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('geography', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ingestion_method', sa.Enum('RSS_POLL', 'WEB_SCRAPE', 'API', 'MANUAL', name='ingestion_method'), nullable=False),
    sa.Column('robots_txt_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('canonical_title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('geography', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('novelty_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'SINGLE_SOURCE', 'MULTI_SOURCE', 'PRIMARY_SOURCE_BACKED', 'VERIFIED', 'DISPUTED', 'CORRECTED', name='verification_status'), nullable=False),
    sa.Column('editorial_status', sa.Enum('INCOMING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED', name='editorial_status'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'CONTRIBUTOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('articles',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('processing_status', sa.Enum('DISCOVERED', 'EXTRACTED', 'SCOUTED', 'CLUSTERED', 'FAILED', name='article_processing_status'), nullable=False),
    sa.Column('scout_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_hash'), 'articles', ['hash'], unique=False)
    op.create_table('editorial_reviews',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('VIEWED', 'EDITED_TITLE', 'EDITED_SUMMARY', 'MERGED', 'SPLIT', 'VERIFICATION_SET', 'APPROVED', 'REJECTED', 'CORRECTION_ISSUED', name='editorial_action'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_entities',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'entity_id')
    )
    op.create_table('story_events',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'event_id')
    )
    op.create_table('agent_runs',
    sa.Column('agent_name', sa.Enum('SCOUT', 'ANALYST', 'VERIFICATION', 'CONTENT', 'ANALYTICS', 'EDITORIAL_ASSISTANT', name='agent_name'), nullable=False),
    sa.Column('trigger', sa.Enum('SCHEDULED', 'MANUAL', 'EVENT', name='agent_trigger'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='agent_run_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_articles',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('cluster_method', sa.Enum('HASH', 'TITLE_SIMILARITY', 'SEMANTIC', 'ENTITY_OVERLAP', 'MANUAL', name='cluster_method'), nullable=False),
    sa.Column('cluster_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'article_id')
    )
    op.create_table('agent_tasks',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Enum('SCOUT', 'ANALYST', 'VERIFICATION', 'CONTENT', 'ANALYTICS', 'EDITORIAL_ASSISTANT', name='agent_name'), nullable=False),
    sa.Column('input_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_output_schema', sa.String(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', 'FAILED', 'ESCALATED', name='agent_task_status'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('token_count_input', sa.Integer(), nullable=True),
    sa.Column('token_count_output', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('error_state', sa.String(), nullable=True),
    sa.Column('human_approval_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'WEBSITE', 'X', name='platform'), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('media_reference', sa.String(), nullable=True),
    sa.Column('content_label', sa.Enum('REPORTING', 'ANALYSIS', 'OPINION', 'SPONSORED', 'POLITICAL_COMMUNICATION', name='content_label'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REGENERATING', 'READY_FOR_REVIEW', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='content_status'), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by_agent_task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generated_by_agent_task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('watch_time_seconds', sa.Integer(), nullable=True),
    sa.Column('website_sessions', sa.Integer(), nullable=True),
    sa.Column('avg_time_on_page_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('agent_task_id', sa.UUID(), nullable=True),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='approval_decision'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'WEBSITE', 'X', name='platform'), nullable=False),
    sa.Column('platform_post_id', sa.String(), nullable=True),
    sa.Column('platform_url', sa.String(), nullable=True),
    sa.Column('attempt_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'RETRYING', name='distribution_attempt_status'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribution')
    op.drop_table('approvals')
    op.drop_table('analytics')
    op.drop_table('content')
    op.drop_table('agent_tasks')
    op.drop_table('story_articles')
    op.drop_table('agent_runs')
    op.drop_table('story_events')
    op.drop_table('story_entities')
    op.drop_table('editorial_reviews')
    op.drop_index(op.f('ix_articles_hash'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stories')
    op.drop_table('sources')
    op.drop_table('events')
    op.drop_index(op.f('ix_entities_canonical_key'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
