"""dedup indexes: pg_trgm title index, unique source+hash

Revision ID: 89dee3155d70
Revises: 0a7d046e9057
Create Date: 2026-08-13 05:24:49.214210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89dee3155d70'
down_revision: Union[str, None] = '0a7d046e9057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articles_title_trgm', 'articles', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_unique_constraint('uq_articles_source_hash', 'articles', ['source_id', 'hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_articles_source_hash', 'articles', type_='unique')
    op.drop_index('ix_articles_title_trgm', table_name='articles', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###
    # pg_trgm extension is left installed on downgrade -- it's a shared, harmless resource.
